trigger: none  # Disables automatic CI trigger for the downstream pipeline
pr: none  # Prevents PR triggers from affecting the downstream pipeline
resources:
  pipelines:
    - pipeline: deploy-pipeline-upstream
      source: praveena263.deploy_pipeline
      trigger: true

pool:
  vmImage: ubuntu-latest
container: mcr.microsoft.com/playwright:v1.48.2-noble

stages:
- stage: Smoke
  jobs:
    - job: Smoke_Testing
      steps:
        - script: echo "Executing Smoke Tests"
        - script: echo "Completed Smoke Test - passed"

- stage: Cypress
  dependsOn: Smoke
  jobs:
    - job: Cypress_Tests
      steps:
        - script: echo "Executing Cypress Tests"
        - script: echo "Completed Cypress Tests - Passed"
       

- stage: Playwright
  dependsOn: Cypress
  jobs:
    - job: Playwright_Tests
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18'
        displayName: 'Install Node.js'
      - script: npm ci
        displayName: 'npm ci'
      - script: npx playwright test
        displayName: 'Run Playwright tests'
        env:
          CI: 'true'
      - publish: $(System.DefaultWorkingDirectory)/playwright-report/index.html
        artifact: Results
        condition: succeededOrFailed()
      - task: PublishTestResults@2
        displayName: 'Publish Junit test results'
        inputs:
          searchFolder: 'test-results'
          testResultsFormat: 'JUnit'
          testResultsFiles: 'e2e-junit-report.xml'
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: 'Playwright JUnit Report'
        condition: succeededOrFailed()
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: playwright-report
          artifact: playwright-report
          publishLocation: 'pipeline'
        condition: succeededOrFailed()
