trigger: none  # Disable automatic trigger for this pipeline
pr: none  # Prevent PR triggers from affecting this pipeline

resources:
  pipelines:
    - pipeline: deploy-pipeline-upstream
      source: praveena263.deploy_pipeline
      trigger: true  # Ensures this pipeline runs after the upstream completes



stages:
  - stage: Smoke
    jobs:
      - job: Smoke_Testing
        container: mcr.microsoft.com/playwright:v1.48.2-noble
        steps:
          - script: echo "Executing Smoke Tests"
          - script: echo "Completed Smoke Test - passed"

  - stage: Cypress
    dependsOn: Smoke
    jobs:
      - job: Cypress_Tests
        container: mcr.microsoft.com/playwright:v1.48.2-noble
        steps:
          - script: echo "Executing Cypress Tests"
          - script: echo "Completed Cypress Tests - Passed"

  - stage: Playwright
    dependsOn: Smoke
    jobs:
      - job: Playwright_Tests
        container: mcr.microsoft.com/playwright:v1.48.2-noble
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18'
            displayName: 'Install Node.js'

          - script: npm ci
            displayName: 'npm ci'

          - script: npx playwright test
            displayName: 'Run Playwright tests'
            env:
              CI: 'true'

          - publish: $(System.DefaultWorkingDirectory)/playwright-report/index.html
            artifact: All_Results
            condition: succeededOrFailed()

          - task: PublishTestResults@2
            displayName: 'Publish Junit test results'
            inputs:
              searchFolder: 'playwright-report'
              testResultsFormat: 'JUnit'
              testResultsFiles: 'e2e-junit-report.xml'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'Playwright JUnit Report'
              publishLocation: 'pipeline'
            condition: succeededOrFailed()

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/playwright-report
              artifact: playwright-report
              publishLocation: 'pipeline'
            condition: succeededOrFailed()
  
  - stage: Playwright_Matrix_Sharded
    dependsOn: Smoke
    jobs:
      - job: Playwright_Tests
        container: mcr.microsoft.com/playwright:v1.48.2-noble
        strategy:
          matrix:
            chromium-1:
              project: chromium
              shard: 1/2
            chromium-2:
              project: chromium
              shard: 1/2
            firefox-1:
              project: firefox
              shard: 1/2
            firefox-2:
              project: firefox
              shard: 1/2
            webkit-1:
              project: webkit
              shard: 1/2
            webkit-2:
              project: webkit
              shard: 1/2
        steps:
          - script: npm ci
            displayName: 'npm ci'

          - script: npx playwright test --project=$(project) --shard=$(shard)
            displayName: 'Run Playwright tests'
            env:
              CI: 'true'
          - publish: $(System.DefaultWorkingDirectory)/playwright-report/index.html
            artifact: $(project)_Results
            condition: succeededOrFailed()